spring:
  application:
    name: reddit-clone-final-project
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/reddit-clone-final-project

############# Mail Properties ###########################################
  mail:
    host: "sandbox.smtp.mailtrap.io"
    port: 2525
    username: b9eda48fdec154
    password: ee6270ce53b66c
    protocol: smtp
############# security ###########################################
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-.....okta.com/oauth2/default
############# Jwt ###########################################
jwt:
  expiration:
    time: 900000

server:
  port: 8080
